### ISSUE TITLE
Unstable babel plugins

### ISSUE THREAD

**Issue by bfanger** [noprotocol/np-vue#1]
The babel plugins in the preset-stage-2 are in "Draft" status and features may change or be removed.

Using them should not be the default, but opt-in.

**Stages:**  
stage-0 experiment 
stage-1 proposal
stage-2 draft
stage-3 candidate
stage-4 node 4+

**Comment by theddes** [comment]
Made it optional: b45b64f4cad2bc7f0f9bc3fedf47b2c4b8141ca1
